/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CatsAreAwesome;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.PrintWriter;
import java.util.Random;
import java.util.Scanner;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin-PC
 */
public class Chatting2 extends javax.swing.JFrame {
 private String username;
    User u = new User(); //added
    Remind r = new Remind();
    public Chatting2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    /**
     * Creates new form Chatting2
     */
    public Chatting2(String name) {
        initComponents();
        username = name;
        userDisplay.setText("Talk to your cat!");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public String file() {
        String str = "";
        try {
            Scanner sc = new Scanner(new FileInputStream("active.txt"));
            while (sc.hasNext()) {
                str = sc.next();
            }
            sc.close();
        } catch (Exception e) {
        }
        return str;
    }

    public void close() {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    cat cat;

    public Remind readobject() {
        try {
            FileInputStream fileOut = new FileInputStream(file());
            ObjectInputStream objectOut = new ObjectInputStream(fileOut);
            Remind c = (Remind) objectOut.readObject();
            objectOut.close();
            return c;
        } catch (Exception ex) {
            return null;
        }
    }
    public void write(String s, int i) {
        try {
            switch (i) {
                case 1: {
                    PrintWriter p = new PrintWriter(new FileOutputStream("src\\talk.txt", true));
                    p.print(s + "\n");
                    p.close();
                    break;
                }
                case 2: {
                    PrintWriter p = new PrintWriter(new FileOutputStream("src\\talk.txt"));
                    System.out.println("Clearing chat ");
                    p.print(s);
                    p.close();
                    break;
                }
            }
        } catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Didnt record that");
        }

    }
    public void read(){
        String s="";
        try{
            Scanner in= new Scanner(new FileInputStream("src\\talk.txt"));
            while(in.hasNextLine()){
                s+=in.nextLine()+"\n";
                userDisplay.setText(s);
            }
            in.close();
        }catch(FileNotFoundException e){}
    }

    class cat {

        
    
}

    Remind c  = readobject();
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userDisplay = new javax.swing.JTextPane();
        userInput = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 51));

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Talk to your cat!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        userDisplay.setEditable(false);
        jScrollPane1.setViewportView(userDisplay);

        userInput.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                userInputInputMethodTextChanged(evt);
            }
        });
        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        jButton2.setText("Talk");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("End Talk");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if(userInput.getText().trim().isEmpty())
        JOptionPane.showMessageDialog(null, "Empty chat ");
        else
        {
            String s =userInput.getText().trim();
        write(s,1);
        write(r.data[0]+" : Meow",1);
        int catLevel=r.LEVEL;
        
        sound(soundFile(catLevel));//put filename
        
        read();
        userInput.setText("\0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        int test =JOptionPane.showConfirmDialog(
//            null,
//            "Do you want to close ?",
//            "CONFIRM",
//            JOptionPane.YES_OPTION);
//        if(test==0)
//        {  
//           write("\0",2);
//           
//           new Main().setVisible(true);
//        close();
//        }      
// TODO add your handling code here:
        dispose();
        Main m = new Main();
        m.setVisible(true);
        m.setLocationRelativeTo(null);
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void userInputInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_userInputInputMethodTextChanged
        
    }//GEN-LAST:event_userInputInputMethodTextChanged

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed
private  void sound(String filename){
//** add this into your application code as appropriate
// Open an input stream  to the audio file.

  try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(filename).getAbsoluteFile());
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch(Exception ex) {
        System.out.println("Error with playing sound.");
        ex.printStackTrace();
    }
}
private String soundFile(int catLevel){
    
    catLevel = r.LEVEL;
    Random r= new Random();
    int rand=r.nextInt(12);
    catLevel=1;
    
    switch(catLevel){
        
        case 1:
            
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";  
        case 2:
           
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            
            
        case 3:
            if(rand==0){
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            
        case 4:
            if(rand==0){
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else{
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            
        case 5:
            if(rand==0){
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==2){
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==3)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1453940411.wav";
            else
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1977450526.wav";
        case 6 :
            if(rand==0){
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==2){
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==3)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1453940411.wav";
            else
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1977450526.wav";
        case 7:
            if(rand==0){
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==2){
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==3)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1453940411.wav";
            else if(rand==4)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1977450526.wav";
            else
                return "C:\\Users\\Admin-PC\\Downloads\\Cat_Meow_2-Cat_Stevens-2034822903.wav";
            
        case 8:    
            if(rand==0){
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==2)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            else if(rand==3)
                 return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1453940411.wav";
            else if(rand==4)
                 return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1977450526.wav";
            else if(rand==5)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat_Meow_2-Cat_Stevens-2034822903.wav";
            else 
                return "C:\\Users\\Admin-PC\\Downloads\\The Cats Meow-SoundBible.com-189817172.wav";    
            
            
        case 9:  
            if(rand==0){
           return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==2)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            else if(rand==3)
                 return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1453940411.wav";
            else if(rand==4)
                 return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1977450526.wav";
            else if(rand==5)
                 return "C:\\Users\\Admin-PC\\Downloads\\Cat_Meow_2-Cat_Stevens-2034822903.wav";
            else if(rand==6) 
                 return "C:\\Users\\Admin-PC\\Downloads\\The Cats Meow-SoundBible.com-189817172.wav"; 
            else
                return "C:\\Users\\Admin-PC\\Downloads\\TomCat-Mr_Smith-2055290520.wav";   
            
        case 10: 
            if(rand==0){
                return "C:\\Users\\Admin-PC\\Downloads\\Kitten Meow-SoundBible.com-1295572573.wav";
            }
            else if(rand==1){
                return"C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            }
            else if(rand==2)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meowing-SoundBible.com-781322082.wav";
            else if(rand==3)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1453940411.wav";
            else if(rand==4)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat Meow-SoundBible.com-1977450526.wav";
            else if(rand==5)
                return "C:\\Users\\Admin-PC\\Downloads\\Cat_Meow_2-Cat_Stevens-2034822903.wav";
            else if(rand==6) 
                return "C:\\Users\\Admin-PC\\Downloads\\The Cats Meow-SoundBible.com-189817172.wav"; 
            else if(rand==7)
                return "C:\\Users\\Admin-PC\\Downloads\\TomCat-Mr_Smith-2055290520.wav"; 
            else
                return "C:\\Users\\Admin-PC\\Downloads\\6_Cat_Meows-Mr_Smith-656280250.wav";    
            
             }
        return null;
    
   
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chatting2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chatting2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane userDisplay;
    private javax.swing.JTextField userInput;
    // End of variables declaration//GEN-END:variables
}
